from typing import List
from uuid import UUID
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from core.database import get_db
from models.project import Project
from models.test_case import TestCase, TestStep
from models.environment import Environment
from schemas import (
    TestCaseCreate, TestCaseResponse, GenerateTestCaseRequest,
)
from services.planner import planner
from core.logging import get_logger

logger = get_logger(__name__)
router = APIRouter()


@router.post("/projects/{project_id}/test-cases/generate", response_model=TestCaseResponse, status_code=status.HTTP_201_CREATED)
async def generate_test_case(
    project_id: UUID,
    request: GenerateTestCaseRequest,
    db: AsyncSession = Depends(get_db),
):
    project = await db.get(Project, project_id)
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    env = None
    if request.environment_id:
        env = await db.get(Environment, request.environment_id)
        if not env or env.project_id != project_id:
            raise HTTPException(status_code=404, detail="Environment not found")
    
    # Generate steps using planner
    steps = await planner.generate_steps(
        intent=request.intent,
        project_id=project_id,
        environment_id=request.environment_id,
        context=request.context,
    )
    
    step_data = []
    for i, step in enumerate(steps):
        step_data.append({
            "id": str(UUID(int=0)),  # Placeholder, will be generated by DB
            "order": i,
            "action": step.action,
            "target": step.target,
            "locator": step.locator,
            "locator_strategy": step.locator_strategy,
            "value": step.value,
            "options": step.options or {},
            "assertion": step.assertion,
            "description": step.description,
            "continue_on_failure": step.continue_on_failure,
        })
    
    test_case = TestCase(
        project_id=project_id,
        environment_id=request.environment_id,
        name=f"Generated: {request.intent[:50]}",
        description=request.intent,
        steps=step_data,
        tags=["generated"],
    )
    db.add(test_case)
    await db.commit()
    await db.refresh(test_case)
    
    logger.info("test_case_generated", test_case_id=str(test_case.id), project_id=str(project_id))
    return TestCaseResponse.model_validate(test_case)